using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppSDK.Managers.UiManager
{
    public interface IUiManager<T>
    {
        //T addTo(ref T t);
        //T add(params T[] t);
        //T Is(int x);
        //T IsDesktop(string x);
        //T IsMobile(string x);
        //T Mobile(int x);
        //T Tablet(int x);
        //T Desktop(int x);
        //T Wide(int x);
        //T FullHD(int x);
        //T IsFluid();
        //T IsRight();
        //T IsLeft();
        //T IsCentered();
        //T IsHalf();
        //T IsMultiline();
        //T IsNarrow();
        //T IsSmall();
        //T IsMedium();
        //T IsLarge();
        //T IsWhite();
        //T IsLight();
        //T IsDark();
        //T IsBlack();
        //T IsLink();
        //T IsPrimary();
        //T IsInfo();
        //T IsSuccess();
        //T IsWarning();
        //T IsDanger();
        //T IsOutlined();
        //T IsInverted();
        //T IsButton();
        //T IsHovered();
        //T IsFocused();
        //T IsActive();
        //T IsLoading();
        //T IsSidebarMenu();
        //T IsHiddenMobile();
        //T IsMainContent();
        //T IsNavItem();
        //T IsNavMenu();
        //T IsMenuList();
        //T isActiveF(string functionName, params string[] vars);
        //T ContentF(params string[] vars);
        //T Div(string classes = null, string content = null);
        //T Conainer(string classes = null);
        //T Row(string classes = null);
        //T Col(int desktop, int mobile, string classes = null);
        //T Section(string classes = null);
        //T Buttun(string classes = null, string content = null);
        //T AButtun(string classes = null, string content = null);
        //T P(string content = null);
        //T TD(string content = null, string classes = null);
        //T TR(string classes = null);
        //T Box(string classes = null);
        //T Notification(string content = null);
        //T tag(string content);
        //T Article(string title, string content);
        //T Nav(string brandImage, string brandLink, T left, T right, string navid);
        //T Menu();
        //T MenuGroup(string label, T ul);
        //T NavLink(string link, string content = null, string classes = null);
        //T A(string link, string content = null, string classes = null);
        //T Ul(string classes = null);
        //T Li(string classes = null);
        //T H1(string content = null);
        //T H2(string content = null);
        //T H3(string content = null);
        //T H4(string content = null);
        //T H5(string content = null);
        //T H(int size, string content = null);
        //T Block();
        //T Form(string formid = null);
        //T Input(string inputid, string _type = "text", string placeholder = null);
        //T Label(string content);
        //T Control();
        //T Field(string label, string inputid, string _type = "text", string placeholder = null);
        //T Table(T[] trs, params string[] threads);
        //T Table(T template, params string[] threads);
        //T Template(string classes = null);
        //T Span(string classes = null);
        //T Img(string link, int width, int height);
    }
}
